# Generated by Django 5.1 on 2024-09-08 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_usersexercise_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='chosen_users_exercises',
            field=models.ManyToManyField(related_name='workout_custom', to='main.usersexercise'),
        ),
    ]
