# Generated by Django 5.1 on 2024-09-08 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_workout_chosen_users_exercises'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workout',
            name='users_exercises',
        ),
        migrations.RemoveField(
            model_name='workout',
            name='chosen_users_exercises',
        ),
        migrations.DeleteModel(
            name='UsersExercise',
        ),
    ]
