# Generated by Django 5.1 on 2024-09-09 16:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_workout_users_exercises_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField(default=0)),
                ('height', models.FloatField(default=0)),
                ('bodyfat', models.FloatField(default=0)),
                ('waist', models.FloatField(default=0)),
                ('chest', models.FloatField(default=0)),
                ('thighs', models.FloatField(default=0)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users_stats', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
