# Generated by Django 5.1 on 2024-09-09 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_userstats'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userstats',
            name='bodyfat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userstats',
            name='chest',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userstats',
            name='height',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userstats',
            name='thighs',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userstats',
            name='waist',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userstats',
            name='weight',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
