# Generated by Django 5.1 on 2024-09-09 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_userstats_bodyfat_alter_userstats_chest_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('weightloss', 'Похудение'), ('bulk', 'Набор веса'), ('waist', 'Уменьшение талии'), ('cut', 'Сушка')], default='other', max_length=10)),
                ('progress', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='userstats',
            name='chest',
        ),
        migrations.RemoveField(
            model_name='userstats',
            name='thighs',
        ),
    ]
