# Generated by Django 5.1 on 2024-09-09 22:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_goal_remove_userstats_chest_remove_userstats_thighs'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='users_goals', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
