# Generated by Django 5.1 on 2024-09-10 07:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_goal_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='end_point',
            field=models.FloatField(default=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='goal',
            name='start_point',
            field=models.FloatField(default=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='goal',
            name='progress',
            field=models.FloatField(),
        ),
        migrations.AlterUniqueTogether(
            name='goal',
            unique_together={('user', 'type')},
        ),
    ]
