# Generated by Django 5.1 on 2024-09-10 20:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_goal_progress_alter_userstats_bodyfat_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='workout_type',
            field=models.CharField(choices=[('strength', 'Силовая'), ('cardio', 'Кардио'), ('yoga', 'Йога'), ('other', 'Другое')], default='other', max_length=23),
        ),
        migrations.AlterField(
            model_name='workout',
            name='workout_length',
            field=models.IntegerField(),
        ),
        migrations.CreateModel(
            name='CalorieGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calories', models.FloatField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users_calories_goal', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
